name = "Assistant"
maintainers = ["You"]
enabled = false

[instructions]
team = "your team"
site ="your site"
instruction = "{persona}\n\n{tool_instructions}\n\n{scene_instructions}"
persona = "You are {name}, an AI assistant powered by an LLM ran on-premises by {team} at {site}."
scene_instructions = "You have access to an instant messaging service that enables communication between members of {team}.  Continue the conversation history provided in Input"
timestamp_instructions = "A timestamp will accompany each message, surrounded by brackets.  When referring to the time, do so in a natural human-readable way"
tool_instructions = "You have access to the following tools:\n{tools}To use a tool, respond with `invoke tool.function(arg_foo = \"lorem\", arg_bar = 42)` where the tool, function and arguments appropriately complement the tool you wish to use"
tool_entry_template = "{tool_name}: {tool_desc}\n{func_entries}\n"
func_entry_template = "  - `{tool_slug}.{func_slug}`: {func_desc}\n    Args:{arg_entries}\n"
args_entry_template = "      - `{arg_slug}` (`{arg_type}`): {arg_desc}"

[cutoff]
enabled = true
phrase = "[put a memorable cutoff phrase here in case of unexpected behaviors requiring sudden shutdowns]"
hint = "[and give yourself a hint to optionally implement in case you need a reminder]"
message = "Emergency cutoff activated.  {name} is how halted."

[tunables]
model_file = "example/some-model.toml"
model_library = "${PWD}/.model_library"

[tunables.generation]
frequency_penalty = 1.07
max_tokens = 1024
presence_penalty = 0.0
seed = 42
temperature = 0.0
top_p = 1.0
top_k = -1

[tunables.generation.mirostat]
mode = 0
eta = 0.1
tau = 5.0

[interfaces]
enabled = ["zulip"]

[interfaces.zulip]
key = "putyourkeyhere"
email = "somebott@chat.your.org"
site = "chat.your.org"
privileged_users = ["you@chat.your.org"]

[tools]
enabled = ["web", "inspector"]

[tools.web]
search_uri = "https://stract.com/beta/api/search"